import { Inter } from "next/font/google"
import "./globals.css"
import GlobalContextProvider from "@/context/GlobalContextProvider"
import GetPosts from "@/utils/getPosts"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const posts = await GetPosts()

  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider posts={posts}>{children}</GlobalContextProvider>
      </body>
    </html>
  )
}
